<h1>Рабочая тетрадь 2. Основы Python</h1>

---
## Мысливец Леонид Владимирович

### Библиотека NumPy
```
NumPy (NumericalPython) - это библиотека Python с открытым
исходным кодом, которая используется практически во всех областях науки
и техники. Это универсальный стандарт для работы с числовыми данными в
Python. 
    Если у вас уже есть Python, вы можете установить NumPy с помощью
командной строки:
  pip install numpy
    Чтобы начать использовать NumPy необходимо импортировать
соответствующую библиотеку:
  import numpy as np
    Основным объектом NumPy является однородный многомерный
массив (в numpy называется numpy.ndarray). Это многомерный массив
элементов (обычно чисел), одного типа.
    Наиболее важные атрибуты объектов ndarray:
  ndarray.ndim - число измерений (чаще их называют "оси") массива.
  ndarray.shape - размеры массива, его форма. Это кортеж натуральных
чисел, показывающий длину массива по каждой оси. Для матрицы из n строк
и m столбов, shape будет (n,m). Число элементов кортежа shape равно ndim.
  ndarray.size - количество элементов массива. Очевидно, равно
произведению всех элементов атрибута shape.
  ndarray.dtype - объект, описывающий тип элементов массива. Можно
определить dtype, используя стандартные типы данных Python. NumPy здесь
предоставляет целый букет возможностей, как встроенных, например: bool_,
character, int8, int16, int32, int64, float8, float16, float32, float64, complex64,
object_, так и возможность определить собственные типы данных, в том
числе и составные.
ndarray.itemsize - размер каждого элемента массива в байтах.
ndarray.data - буфер, содержащий фактические элементы массива.
Обычно не нужно использовать этот атрибут, так как
обращаться к элементам массива проще всего с помощью индексов.
```
```
    Подробнее о массивах в NumPy можно найти в официальной докукументации
``` 
https://numpy.org/doc/stable/user/absolute_beginners.html



***Пример:*** Создать массив 5x2. Создать массив 5x2. Вывести все значения массива, значение элемента с индексом (3,1) и второй столбец. Индексация начинается с нуля.

In [1]:
import numpy as np
x=np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])
print(x)
print(x[3][1])
print(x[1])

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
8
[3 4]


***Пример:*** Выполнить следующее:
1. Создать вектор (одномерный массив) размера 10, заполненный нулями.
2. Создать вектор размера 10, заполненный единицами.
3. Создать вектор размера 10, заполненный заданным числом. 4. Создать вектор со значениями от 10 до 19.

In [2]:
a=np.zeros(10)
b=np.ones(10)
c=np.full(10,5)
d=np.arange(10,20)
print(a,"\n",b,"\n",c,"\n",d)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 
 [5 5 5 5 5 5 5 5 5 5] 
 [10 11 12 13 14 15 16 17 18 19]


In [3]:
Z=np.random.random((10,10))
Zmin, Zmax, Zmean=Z.min(), Z.max(), Z.mean()
print(Zmin,Zmax,Zmean)

0.007525545160372071 0.9881855426091447 0.5297640697266952


***Пример:*** Задать матрицу размерности 5 на 5 и поменять 2 строки в матрице местами.

In [4]:
A=np.arange(25).reshape(5,5)
A[[0,1]]=A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


***Пример:*** Отсортировать массив.

In [5]:
arr=np.array([2,1,5,3,7,4,6,8])
print(np.sort(arr))

[1 2 3 4 5 6 7 8]


***Задание:*** Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и
единицами.

In [6]:
Z = np.zeros((8,8))
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)
# Z = np.tile(np.array([[0,1],[1,0]]), (4,4))
# print(Z)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


***Задание:*** Создать 5x5 матрицу со значениями в строках от 0 до 4. Для создания
необходимо использовать функцию arrange.

In [7]:
import numpy as np
# Z=np.arange(0,5)
# d = np.array([Z]*5)
# print(d)

# A=np.arange(25).reshape(5,5)
# A[[1,1]]=A[[0,0]]
# A[[2,2]]=A[[0,0]]
# A[[3,3]]=A[[0,0]]
# A[[4,4]]=A[[0,0]]
# print(A)

# Z=np.arange(25).reshape(5,5)
# print(np.argsort(Z))

Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


***Задание:*** Создать массив 3x3x3 со случайными значениями.

In [8]:
Z=np.random.random((3,3,3))
print(Z)

[[[0.15712287 0.80461942 0.73553998]
  [0.83479532 0.70205506 0.59403331]
  [0.09895271 0.10996146 0.64992472]]

 [[0.58762995 0.62634571 0.43845899]
  [0.43490622 0.60918953 0.6674855 ]
  [0.69661207 0.21019204 0.29450675]]

 [[0.83878089 0.23157524 0.2586876 ]
  [0.42355128 0.31172082 0.91466832]
  [0.14143192 0.2663859  0.18825242]]]


***Задание:*** Создать матрицу с 0 внутри, и 1 на границах.

In [9]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


***Задание:*** Создайте массив и отсортируйте его по убыванию.

In [10]:
a = np.random.randint(10,size=15)
print(np.sort(a)[::-1])

[9 8 7 6 6 5 3 3 3 3 2 1 0 0 0]


***Задание:*** Создайте матрицу, выведите ее форму, размер и размерность.

In [11]:
Z = np.ones((5,5))
print(Z.size)
print(Z.shape)
print(len(Z),'/',len(Z[0]))
if len(Z)!= (len(Z[0])):
    print('прямоугольник')
else: print('квадрат')

25
(5, 5)
5 / 5
квадрат


### Библиотека Pandas
```
Первым шагом в любом начинании в области машинного обучения является введение исходных данных в систему. Исходные данные могут вводиться вручную, содержаться в файле или храниться в интернете в каком- либо формате. Кроме того, часто требуется получить данные из нескольких источников.
Библиотека pandas – это удобный и быстрый инструмент для работы с данными, обладающий большим функционалом. Если очень кратко, то pandas – это библиотека, которая предоставляет очень удобные с точки зрения использования инструменты для хранения данных и работе с ними.
Библиотека pandas присутствует в стандартной поставке Anaconda.
Если же ее там нет, то его можно установить отдельно. Для этого введите командной строке:
    pip install pandas
Для импорта библиотеки используйте команду:
import pandas as pd
Библиотека pandas предоставляет две ключевые структуры данных: Series и DataFrame.
Series – это одномерная структура данных, ее можно представить, как таблицу с одной строкой. С Series можно работать как с обычным массивом (обращаться по номеру индекса), и как с ассоциированным массивом, когда можно использовать ключ для доступа к элементам данных.
DataFrame – это двумерная структура. Идейно она очень похожа на обычную таблицу, что выражается в способе ее создания и работе с ее элементами.
```

 ***Пример:*** Создать Series из списка Python, словаря Python, и массива Numpy (установить буквенные метки для последнего).

In [12]:
import pandas as pd
lst = [1, 2, 3, 4, 5]
d = {'a':1, 'b':2, 'c':3}
ndarr = np.array([1, 2, 3, 4, 5])
s1 = pd.Series(lst)
s2 = pd.Series(d)
s3 = pd.Series(ndarr, ['a', 'b','c', 'd', 'e'])
print(s1)
print(s2)
print(s3)

0    1
1    2
2    3
3    4
4    5
dtype: int64
a    1
b    2
c    3
dtype: int64
a    1
b    2
c    3
d    4
e    5
dtype: int64


***Пример:*** Дано два Series. Напечатать их первые элементы и все элементы после третьего (во втором фрейме)

In [13]:
s1 = pd.Series([1, 2, 3, 4, 5], ['a', 'b', 'c', 'd', 'e']) 
s2 = pd.Series([5, 4, 3, 2, 1])
print(s1['a'])
print(s2[0])
print(s2[3:])

1
5
3    2
4    1
dtype: int64


***Пример:*** Создайте новый фрейм данных.

In [14]:
dataframe = pd.DataFrame()
dataframe['Имя'] = ['Джеки Джексон', 'Стивен Стивенсон']
dataframe['Возраст'] = [38, 25]
dataframe['Водитель'] = [True, False]
dataframe


Имя  Возраст  Водитель
0     Джеки Джексон       38      True
1  Стивен Стивенсон       25     False

***Пример:*** Загрузите фрейм данных по ссылке:
https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv

In [15]:
# Создать URL-адрес
url = 'https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv' 
# Загрузить данные
dataframe = pd.read_csv(url)
# Показать пять строк
dataframe. head(5)

Name PClass    Age     Sex  \
0                   Allen, Miss Elisabeth Walton    1st  29.00  female   
1                    Allison, Miss Helen Loraine    1st   2.00  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.00    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.00  female   
4                  Allison, Master Hudson Trevor    1st   0.92    male   

   Survived  SexCode  
0         1        1  
1         0        1  
2         0        0  
3         0        1  
4         1        0

***Пример:*** Пронализировать характеристики фрейма данных.


Одна из самых простых вещей, которые мы можем сделать после загрузки данных, – это взглянуть на первые несколько строк с помощью метода head. На последние строки можно посмотреть с помощью функции tail. Мы также можем взглянуть на количество строк и столбцов: dataframe.shape. Кроме того, используя метод describe, мы можем получить описательную статистику для любых числовых столбцов.

In [16]:
dataframe.head(2)
dataframe. tail(3)
dataframe.shape
dataframe.describe()

Age     Survived      SexCode
count  756.000000  1313.000000  1313.000000
mean    30.397989     0.342727     0.351866
std     14.259049     0.474802     0.477734
min      0.170000     0.000000     0.000000
25%     21.000000     0.000000     0.000000
50%     28.000000     0.000000     0.000000
75%     39.000000     1.000000     1.000000
max     71.000000     1.000000     1.000000

Более подробно с возможностями работы с фреймами данных можно узнать по ссылке ниже: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html

***Пример:*** Для выбора одной или нескольких строк, либо значений, можно использовать методы 1ос или iloc.



In [17]:
dataframe.iloc[1:4]

Name PClass   Age     Sex  \
1                    Allison, Miss Helen Loraine    1st   2.0  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.0    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.0  female   

   Survived  SexCode  
1         0        1  
2         0        0  
3         0        1

***Пример:*** Требуется отобрать строки фрейма данных на основе некоторого условия. Необходимо сформировать новый фрейм данных из пассажиров первого класса.

In [18]:
dataframe[dataframe['PClass'] == '1st'].head(2)

Name PClass   Age     Sex  Survived  SexCode
0  Allen, Miss Elisabeth Walton    1st  29.0  female         1        1
1   Allison, Miss Helen Loraine    1st   2.0  female         0        1

***Задание:*** Найдитн евклидово расстояние между двумя Series (точками) a и b, не
используя встроенную формулу

In [19]:
a = pd.Series([2, 4, 6, 8])
b = pd.Series([1, 3, 5, 7])
print(sum((a - b)**2)**.5)

print(f'ответ по формуле: {np.linalg.norm(a-b)}')

2.0
ответ по формуле: 2.0


***Задание:*** Найдите в Интернете ссылку на любой csv файл и сформируйте из него фрейм данных (например, коллекцию фреймов данных можно найти здесь: https://github.com/akmand/datasets).


In [20]:
url = 'https://raw.githubusercontent.com/akmand/datasets/main/adult.csv' 
# Загрузить данные
dataframe = pd.read_csv(url)
# Показать пять строк
dataframe. head(3)

age         workclass  education_num      marital_status  \
0   39         State-gov             13       Never-married   
1   50  Self-emp-not-inc             13  Married-civ-spouse   
2   38           Private              9            Divorced   

          occupation   relationship   race gender  hours_per_week  \
0       Adm-clerical  Not-in-family  White   Male              40   
1    Exec-managerial        Husband  White   Male              13   
2  Handlers-cleaners  Not-in-family  White   Male              40   

  native_country  capital income_status  
0  United-States     2174         <=50K  
1  United-States        0         <=50K  
2  United-States        0         <=50K

***Задание:*** Проделайте с получившемся из предыдущего задания фреймом данных
те же действия, что и в примерах 2.2.5-2.2.7.

In [21]:
dataframe.head(2)
dataframe. tail(3)
dataframe.shape
dataframe.describe()

age  education_num  hours_per_week       capital
count  45222.000000   45222.000000    45222.000000  45222.000000
mean      38.547941      10.118460       40.938017   1012.834925
std       13.217870       2.552881       12.007508   7530.315380
min       17.000000       1.000000        1.000000  -4356.000000
25%       28.000000       9.000000       40.000000      0.000000
50%       37.000000      10.000000       40.000000      0.000000
75%       47.000000      13.000000       45.000000      0.000000
max       90.000000      16.000000       99.000000  99999.000000

In [22]:
dataframe.iloc[1:4]

age         workclass  education_num      marital_status  \
1   50  Self-emp-not-inc             13  Married-civ-spouse   
2   38           Private              9            Divorced   
3   53           Private              7  Married-civ-spouse   

          occupation   relationship   race gender  hours_per_week  \
1    Exec-managerial        Husband  White   Male              13   
2  Handlers-cleaners  Not-in-family  White   Male              40   
3  Handlers-cleaners        Husband  Other   Male              40   

  native_country  capital income_status  
1  United-States        0         <=50K  
2  United-States        0         <=50K  
3  United-States        0         <=50K

In [23]:
dataframe[dataframe['gender'] == 'Male'].head(2)

age         workclass  education_num      marital_status       occupation  \
0   39         State-gov             13       Never-married     Adm-clerical   
1   50  Self-emp-not-inc             13  Married-civ-spouse  Exec-managerial   

    relationship   race gender  hours_per_week native_country  capital  \
0  Not-in-family  White   Male              40  United-States     2174   
1        Husband  White   Male              13  United-States        0   

  income_status  
0         <=50K  
1         <=50K

### Работа с числовыми данными

```
    Количественные данные что-то измеряют – будь то размер класса,
ежемесячные продажи или оценки учащихся. Естественным способом представления этих величин является численным (например, 150 студентов, 529 392 продаж).
Нормализация данных — это общепринятая задача предобработки в машинном обучении. Многие алгоритмы предполагают, что все признаки находятся в единой шкале, как правило, от 0 до 1 или от -1 до 1.
    Существует множество способов нормализации значений признаков, чтобы масштабировать их к единому диапазону и использовать в различных моделях машинного обучения. В зависимости от используемой функции, их можно разделить на 2 большие группы: линейные и нелинейные. При нелинейной нормализации в расчетных соотношениях используются функции логистической сигмоиды или гиперболического тангенса. В линейной нормализации изменение переменных осуществляется пропорционально, по линейному закону.
На практике наиболее распространены следующие методы нормализации признаков:
  Минимакс – линейное преобразование данных в диапазоне [0..1], где минимальное и максимальное масштабируемые значения
соответствуют 0 и 1 соответственно;
  Z-масштабирование данных на основе среднего значения и
стандартного отклонения: производят деление разницы между переменной и средним значением на стандартное отклонение.
    При масштабировании данных мы будем использовать одну из популярных библиотек машинного обучения Scikit-learn. Библиотека содержит пакет sklearn.preprocessing, который предоставляет широкие возможности для нормализации данных. Следует отметить, что в целом алгоритмы обучения выигрывают от стандартизации набора данных.
```

***Пример:*** Прошкалируйте числовой признак в диапазон между двумя значениями.

In [24]:
# Загрузить библиотеки
import numpy as np
from sklearn import preprocessing
# Создать признак
feature = np.array([[-500.5], [-100.1], [0], [100.1], [900.9]])
# Создать шкалировщик
minmax_scale = preprocessing.MinMaxScaler(feature_range = (0, 1))
# Прошкалировать признак
scaled_feature = minmax_scale.fit_transform(feature)
#Показать прошкалированный признак
scaled_feature

array([[0.        ],
       [0.28571429],
       [0.35714286],
       [0.42857143],
       [1.        ]])

***Пример:*** Преобразуйте признак, чтобы он имел среднее значение 0 и стандартное
отклонение 1.

In [25]:
x = np.array([[-1000.1], [-200.2], [500.5], [600.6], [9000.9]])
# Создать шкалировщик
scaler = preprocessing.StandardScaler()
# Преобразовать признак
standardized = scaler.fit_transform(x)
# Показать признак
standardized
#Мы можем увидеть эффект стандартизации, обратившись к среднему значению и стандартному отклонению результата нашего решения:
print("Среднее:", round(standardized.mean()))
print("Стандартное отклонение:", standardized.std())

Среднее: 0
Стандартное отклонение: 1.0


***Пример:*** Дан фрейм данных
dfTest = pd.DataFrame({'A':[14.00,90.20,90.95,96.27,91.21],
'B':[103.02,107.26,110.35,114.23,114.68],
'C':['big','small','big','small','small']}) Необходимо масштабировать его числовые столбцы.

In [26]:
import pandas as pd
from sklearn. preprocessing import MinMaxScaler
scaler = MinMaxScaler()
dfTest = pd.DataFrame({'A':[14.00,90.20,90.95,96.27,91.21],
                       'B':[103.02,107.26,110.35,114.23,114.68],
                       'C':['big','small','big','small','small']})

dfTest[['A', 'b']] = scaler.fit_transform(dfTest[['A', 'B']])
dfTest

A       B      C         b
0  0.000000  103.02    big  0.000000
1  0.926219  107.26  small  0.363636
2  0.935335  110.35    big  0.628645
3  1.000000  114.23  small  0.961407
4  0.938495  114.68  small  1.000000

***Задание:*** Загрузить фрейм данных по ссылке: https://raw.githubusercontent.com/akmand/datasets/master/iris.csv. Необходимо выполнить нормализацию первого числового признака (sepal_length_cm) с использованием минимаксного преобразования, а второго (sepal_width_cm) с задействованием z-масштабирования.

In [27]:
from sklearn import preprocessing 
url = 'https://raw.githubusercontent.com/akmand/datasets/master/iris.csv' 
dataframe = pd.read_csv(url)
newdf=pd.DataFrame(data=dataframe, columns=['sepal_length_cm'])
scaler_minm = preprocessing.MinMaxScaler()
scaler_minm.fit(newdf)
scaled_features = scaler_minm.transform(newdf)
df_MinMax = pd.DataFrame(data = scaled_features)

stand_df=pd.DataFrame(data=dataframe, columns=['sepal_width_cm'])
scaler_stand = preprocessing.StandardScaler()
scaler_stand.fit(stand_df)
scaled_featur = scaler_stand.transform(stand_df)
df_Stand = pd.DataFrame(data = scaled_featur)

result = pd.concat([df_MinMax, df_Stand],axis=1,keys=["sepal_length_cm", "sepal_width_cm"])
result.head()

sepal_length_cm sepal_width_cm
                0              0
0        0.222222       1.032057
1        0.166667      -0.124958
2        0.111111       0.337848
3        0.083333       0.106445
4        0.194444       1.263460